### ISSUE TITLE
npm start fails under raspbian 10

### ISSUE THREAD

**Issue by nlebellier** [hundredrabbits/Orca#179]
hI,

With 
```
pi@raspberrypi:~/audio/Orca/desktop $ node --version && npm --version
v12.13.0
6.12.0
```

After cloning the repo i get this :
```
pi@raspberrypi:~/audio/Orca/desktop $ npm start

> Orca@0.1.0 start /home/pi/audio/Orca/desktop
> electron .

/home/pi/audio/Orca/desktop/node_modules/electron/index.js:14
    throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
    ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at getElectronPath (/home/pi/audio/Orca/desktop/node_modules/electron/index.js:14:11)
    at Object.<anonymous> (/home/pi/audio/Orca/desktop/node_modules/electron/index.js:18:18)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Module.require (internal/modules/cjs/loader.js:849:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/pi/audio/Orca/desktop/node_modules/electron/cli.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! Orca@0.1.0 start: `electron .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the Orca@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2019-10-29T13_50_30_209Z-debug.log
```

**Comment by neauoire** [comment]
Did you:
- do `npm install` as written in the instructions?
- `delete node_modules/electron and try installing again` as written in the error message?

I don't have a RPi with me at the moment to test this.

**Comment by neauoire** [comment]
On raspberry pi, I prefer to use [Orca-c](https://github.com/hundredrabbits/orca-c), it's a lot faster.

**Comment by nlebellier** [comment]
Did you:

> do npm install as written in the instructions?
sure

> delete node_modules/electron and try installing again as written in the error message?
yes 

i will have a look at orca-c

**Comment by bbarham** [comment]
Same issue. Global install of electron@7.1.0 fails with same error as Orca npm install. Node v13.1.0 npm v6.12.1. Really wish I could get this working again. Please let me know if there's anything i can do to help.

**Comment by nlebellier** [comment]
Hi

i try today with the latest version of Orca.

```
pi@raspberrypi:~/audio/Orca/desktop $ npm install

> core-js@3.3.6 postinstall /home/pi/audio/Orca/desktop/node_modules/core-js
> node postinstall || echo "ignore"


> electron@7.1.0 postinstall /home/pi/audio/Orca/desktop/node_modules/electron
> node install.js

(node:1081) UnhandledPromiseRejectionWarning: HTTPError: Response code 404 (Not Found)
    at EventEmitter.<anonymous> (/home/pi/audio/Orca/desktop/node_modules/got/source/as-stream.js:35:24)
    at EventEmitter.emit (events.js:210:5)
    at module.exports (/home/pi/audio/Orca/desktop/node_modules/got/source/get-response.js:22:10)
    at ClientRequest.handleResponse (/home/pi/audio/Orca/desktop/node_modules/got/source/request-as-event-emitter.js:155:5)
    at Object.onceWrapper (events.js:300:26)
    at ClientRequest.emit (events.js:215:7)
    at ClientRequest.origin.emit (/home/pi/audio/Orca/desktop/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:583:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:17)
    at TLSSocket.socketOnData (_http_client.js:456:22)
(node:1081) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1081) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
npm WARN Orca@0.1.0 No description
npm WARN Orca@0.1.0 No repository field.
npm WARN Orca@0.1.0 No license field.

added 165 packages from 137 contributors and audited 346 packages in 9.273s
pi@raspberrypi:~/audio/Orca/desktop $ sudo apt update
Atteint :1 https://deb.nodesource.com/node_12.x buster InRelease
Réception de :2 http://raspbian.raspberrypi.org/raspbian buster InRelease [15,0 kB]
Réception de :3 http://archive.raspberrypi.org/debian buster InRelease [25,2 kB] 
Réception de :4 http://raspbian.raspberrypi.org/raspbian buster/main armhf Packages [13,0 MB]
Réception de :5 http://archive.raspberrypi.org/debian buster/main armhf Packages [259 kB]
13,3 Mo réceptionnés en 16s (856 ko/s)                                                                                                    
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances       
Lecture des informations d'état... Fait
15 paquets peuvent être mis à jour. Exécutez « apt list --upgradable » pour les voir.
pi@raspberrypi:~/audio/Orca/desktop $ npm --version
6.13.0
pi@raspberrypi:~/audio/Orca/desktop $ node --version
v12.13.0
pi@raspberrypi:~/audio/Orca/desktop $ 
```

**Comment by neauoire** [comment]
A whole bunch of people are getting that same error apparently.
https://github.com/electron/electron/issues/20479

**Comment by martinberlin** [comment]
I agree fully that Orca-C works much better in ARM architecture.
Use the C version for slower machines. Is as fast as it can get and even it does not make it slower to catch events like keyboard movements. I definitively like it a lot for this small machines.

**Comment by bbarham** [comment]
Temporary workaround:
After failed **npm install** in **Orca/desktop**

cd node_modules/
mv electron electron_old
cd ..
npm install electron@6.0.12
npm start

This appears to get Orca up and running with latest repo as or 11/10/19. I will test some of the latest changes and note any oddities.
