### ISSUE TITLE
Can't start UDP server

### ISSUE THREAD

**Issue by Kabraxist** [hundredrabbits/Orca#270]
Hey there,

I was trying to use UDP with ORCA, but it seems ORCA can't start UDP server in the latest version. 

The warning I get in Inspector is:
```
udp.js:66 UDP Server error:
 Error: bind EACCES 0.0.0.0:49160
    at dgram.js:321:20
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
(anonymous) @ udp.js:66
```

Platform: Windows 11 N Pro

**Comment by Kabraxist** [comment]
It works well after a restart. Weird.
